# Generated by Django 5.2.1 on 2025-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('runs_scored', models.IntegerField()),
                ('wickets_taken', models.IntegerField()),
                ('match_date', models.DateField()),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
    ]
